// Copyright (c) 2006-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run all tifioctls
LOAD_SUITE tifioctls

CONSECUTIVE

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLSHW-0001
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLSHW-0001
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tifioctls ExampleL \tstdapis\tifioctls.ini SectionExampleL 
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLSHW-0001

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLSHW-0002
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLSHW-0002
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tifioctls ListInterfaces \tstdapis\tifioctls.ini SectionListInterfaces_1
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLSHW-0002

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLSHW-0003
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLSHW-0003
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tifioctls ListInterfaces \tstdapis\tifioctls.ini SectionListInterfaces_2
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLSHW-0003

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLSHW-0004
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLSHW-0004
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tifioctls ListInterfaces \tstdapis\tifioctls.ini SectionListInterfaces_3
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLSHW-0004

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLSHW-0005
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLSHW-0005
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tifioctls ListInterfaces \tstdapis\tifioctls.ini SectionListInterfaces_4
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLSHW-0005



START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLSHW-0008
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLSHW-0008
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 tifioctls TestIfNameIndex
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLSHW-0008

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLSHW-0009
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLSHW-0009
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 tifioctls TestIfIndexToName \tstdapis\tifioctls.ini SectionTestIfIndexToName_1
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLSHW-0009

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLSHW-0010
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLSHW-0010
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 tifioctls TestIfIndexToName \tstdapis\tifioctls.ini SectionTestIfIndexToName_2
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLSHW-0010

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLSHW-0011
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLSHW-0011
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 tifioctls TestIfNameToIndex \tstdapis\tifioctls.ini SectionTestIfNameToIndex_1
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLSHW-0011

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLSHW-0012
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLSHW-0012
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 tifioctls TestSiocGIfIndex \tstdapis\tifioctls.ini SectionTestSiocGIfIndex
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLSHW-0012

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLSHW-0013
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLSHW-0013
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 50 tifioctls Testioctlfile
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLSHW-0013

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLSHW-0014
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLSHW-0014
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 50 tifioctls Testioctl1
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLSHW-0014

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLS-0015
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLS-0015
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 50 tifioctls TestGetIfIPAddr \tstdapis\tifioctls.ini 
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLS-0015

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLS-0016
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLS-0016
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 50 tifioctls TestGetIfAttributes \tstdapis\tifioctls.ini 
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLS-0016

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLS-0017
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLS-0017
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 50 tifioctls TestSetIfAttributes \tstdapis\tifioctls.ini 
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLS-0017

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLS-0018
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLS-0018
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 100 tifioctls TestSetIfDNSSuffix \tstdapis\tifioctls.ini  SectionSetIfDNSSuffix
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLS-0018

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLS-0019
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLS-0019
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 50 tifioctls TestGetIfDNSSuffix \tstdapis\tifioctls.ini 
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLS-0019

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLS-0020
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLS-0020
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 50 tifioctls TestRouteIoctl \tstdapis\tifioctls.ini 
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLS-0020

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLS-0021
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLS-0021
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 50 tifioctls TestNumberOfRoutesIoctl \tstdapis\tifioctls.ini 
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLS-0021

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLS-0022
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLS-0022
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 50 tifioctls TestGetNameServers \tstdapis\tifioctls.ini 
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLS-0022

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLS-0023
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLS-0023
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 50 tifioctls TestSetNameServers \tstdapis\tifioctls.ini SectionSetIfNameServer
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLS-0023

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLS-0024
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLS-0024
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 50 tifioctls TestGetNameServers \tstdapis\tifioctls.ini 
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLS-0024

